<a href="https://colab.research.google.com/github/gaire56/ml_learning/blob/main/maths/Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy Library

In [1]:
import numpy as np

Matrix Addition

Two matrix can be added only if they have the same shape

In [6]:
#Creating two matrices

A = np.array([[2,3], [4,5]])
print(A)
B = np.array([[6,7], [8,9]])
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [7]:
A.shape

(2, 2)

In [8]:
B.shape

(2, 2)

Adding two matrices

In [9]:
sum = A +B
print(sum)

[[ 8 10]
 [12 14]]


In [10]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(10, size=(3,3))
print(matrix_1)
print(matrix_2)

[[7 5 4]
 [6 5 1]
 [0 5 9]]
[[8 1 7]
 [4 7 8]
 [2 6 1]]


In [11]:
sum = np.add(matrix_1, matrix_2) #this is how we can add two matrix
print(sum)

[[15  6 11]
 [10 12  9]
 [ 2 11 10]]


In [12]:
matrix_3 = np.random.randint(10, size=(3,3)) # this is 3X3 matrix
matrix_4 = np.random.randint(10, size=(3,4)) #this is 3X4 matrix
print(matrix_3)
print(matrix_4)

[[7 5 3]
 [1 0 8]
 [7 4 5]]
[[2 4 9 9]
 [7 8 0 7]
 [8 1 2 1]]


In [ ]:
sum2 = np.add(matrix_1, matrix_2) #we cannot add these two matrix because they have different shape
print(sum2)

We get error because shape of matrix_3 and matrix_4 are different

Matrix Subtraction

In [15]:
#creating two matrix
A = np.array([[2,3], [4,5]])
print(A)
B = np.array([[6,7], [8,9]])
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [16]:
difference = B - A
print(difference)

[[4 4]
 [4 4]]


In [19]:
# create two matrices with random values
matrix_1 = np.random.randint(100, size=(3,3))
matrix_2 = np.random.randint(10, size=(3,3))
print(matrix_1)
print(matrix_2)

[[79 28 53]
 [ 3 74 19]
 [88 94 27]]
[[4 7 7]
 [4 4 5]
 [3 6 6]]


In [20]:
diff = np.subtract(matrix_1, matrix_2)
print(diff)

[[75 21 46]
 [-1 70 14]
 [85 88 21]]


we cannot subtract if two matrix have different shape

Multiplying a matrix by a scalar

In [22]:
x = 5
y = np.random.randint(10, size=(4,3))
print(y)

[[4 9 4]
 [1 7 1]
 [0 0 2]
 [7 1 7]]


In [23]:
product = np.multiply(x, y)
print(product)

[[20 45 20]
 [ 5 35  5]
 [ 0  0 10]
 [35  5 35]]


Multiplying 2 Matrices

In [24]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(4,3))
matrix_2 = np.random.randint(10, size=(3,4))
print(matrix_1)
print(matrix_2)

[[4 8 2]
 [3 5 5]
 [7 8 6]
 [5 7 5]]
[[9 0 0 6]
 [0 7 2 0]
 [0 4 0 9]]


In [26]:
product = np.dot(matrix_1, matrix_2)
print(product)

[[36 64 16 42]
 [27 55 10 63]
 [63 80 16 96]
 [45 69 14 75]]


In [27]:
product.shape

(4, 4)

Element wise Matrix multiplication

In [29]:
#create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(10, size=(3,3))
print(matrix_3)
print(matrix_4)

[[6 1 8]
 [4 1 4]
 [1 5 3]]
[[0 9 5]
 [0 9 3]
 [0 4 9]]


In [30]:
product = np.multiply(matrix_3, matrix_4)
print(product)

[[ 0  9 40]
 [ 0  9 12]
 [ 0 20 27]]
