<a href="https://colab.research.google.com/github/gaire56/ml_learning/blob/main/maths/Working_with_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a metrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]]) #
print (matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape #shape commad give us a shape of a matrix

(2, 2)

In [4]:
matrix_2 = np.array([[54, 34, 25], [84, 112, 32], [43, 90, 23]])
print(matrix_2)

[[ 54  34  25]
 [ 84 112  32]
 [ 43  90  23]]


In [5]:
matrix_2.shape

(3, 3)

Creating a metrix with randam values

In [12]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.03201578 0.47807581 0.30717037]
 [0.34139485 0.32079608 0.16189065]
 [0.05559518 0.82054365 0.48519631]]


In [7]:
#Creating matrix with random itizer
random_integer_matrix = np.random.randint(100, size=(5,6))
print(random_integer_matrix)

[[90 68 86 39 28 79]
 [77 80 59 81 61 79]
 [47 67 78 73 58 55]
 [25 59 98 88 24 62]
 [92 27 25 97 98 99]]


Matrix with all the values as 1


In [9]:
matrix_3 = np.ones((5,4))
print(matrix_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
matrix_3 = np.ones((5,4), dtype=int)
print(matrix_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Null Matrix or Zero Matrix

In [14]:
null_matrix = np.zeros((3, 6), dtype=int)
print(null_matrix)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


Indentity Matrix

In [16]:
identity_matrix = np.eye(5, dtype = int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [19]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of a Matrix

In [21]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[59 66 90 62 30]
 [23 61 84 64 29]
 [18 26 65 71 89]
 [73 37 96 55 30]]


In [22]:
#transpost of Matrix a
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[59 23 18 73]
 [66 61 26 37]
 [90 84 65 96]
 [62 64 71 55]
 [30 29 89 30]]
